import type { UniversityGuideline } from "@/lib/guidelines";

const universityNames: Record<string, string> = {
  "tribhuvan-university": "त्रिभुवन विश्वविद्यालय",
  "pokhara-university": "पोखरा विश्वविद्यालय",
  "kathmandu-university": "काठमाडौं विश्वविद्यालय",
  "purwanchal-university": "पूर्वाञ्चल विश्वविद्यालय",
  "mid-western-university": "मध्यपश्चिम विश्वविद्यालय",
  "far-western-university": "सुदूरपश्चिम विश्वविद्यालय",
  "agriculture-and-forestry-university": "कृषि तथा वन विज्ञान विश्वविद्यालय",
  "nepal-sanskrit-university": "नेपाल संस्कृत विश्वविद्यालय",
  "bp-koirala-institute-of-health-sciences":
    "बी.पी. कोइराला स्वास्थ्य विज्ञान प्रतिष्ठान",
};

const phrases: Record<string, string> = {
  "Research Proposal": "अनुसन्धान प्रस्ताव",
  "Research proposals": "अनुसन्धान प्रस्तावहरू",
  "Research Process": "अनुसन्धान प्रक्रिया",
  "Research Methodology": "अनुसन्धान विधि",
  "Research design": "अनुसन्धान डिजाइन",
  "Research approach": "अनुसन्धान दृष्टिकोण",
  "Research question": "अनुसन्धान प्रश्न",
  "Research questions": "अनुसन्धान प्रश्नहरू",
  "Research objectives": "अनुसन्धान उद्देश्यहरू",
  "Research objective": "अनुसन्धान उद्देश्य",
  "Research problem": "अनुसन्धान समस्या",
  "Research context": "अनुसन्धान सन्दर्भ",
  "Research topic": "अनुसन्धान विषय",
  "Research title": "अनुसन्धान शीर्षक",
  "Literature Review": "साहित्य समीक्षा",
  "literature review": "साहित्य समीक्षा",
  "Literature organisation": "साहित्य व्यवस्थापन",
  "Research gap": "अनुसन्धान रिक्तता",
  "Research ethics": "अनुसन्धान नैतिकता",
  "Academic integrity": "शैक्षिक इमानदारी",
  "Academic writing": "शैक्षिक लेखन",
  "Academic requirements": "शैक्षिक आवश्यकताहरू",
  "Academic research": "शैक्षिक अनुसन्धान",
  "Thesis Structure": "थेसिस संरचना",
  "Thesis Submission": "थेसिस पेश",
  "Thesis Protocol": "थेसिस प्रोटोकल",
  "Thesis and Research Work": "थेसिस तथा अनुसन्धान कार्य",
  "Research Progress": "अनुसन्धान प्रगति",
  "Progress Reporting": "प्रगति प्रतिवेदन",
  "Proposal Formatting": "प्रस्ताव फर्म्याटिङ",
  "Proposal Title Page": "प्रस्तावको शीर्षक पृष्ठ",
  "Proposal Components": "प्रस्तावका घटकहरू",
  "Proposal Areas": "प्रस्तावका क्षेत्रहरू",
  "Research Workflow": "अनुसन्धान कार्यप्रवाह",
  "Research Integrity": "अनुसन्धानको इमानदारी",
  "Research Resources": "अनुसन्धान स्रोतहरू",
  "Official Sources": "आधिकारिक स्रोतहरू",
  "Official Proposal Resources": "आधिकारिक प्रस्ताव स्रोतहरू",
  "Programme-Specific Requirements": "कार्यक्रम-विशिष्ट आवश्यकताहरू",
  "Programme-Specific Differences": "कार्यक्रम-विशिष्ट भिन्नताहरू",
  "Before You Submit": "पेश गर्नुअघि",
  "Before Submission": "पेश गर्नुअघि",
  "Final Materials": "अन्तिम सामग्री",
  "Final Version": "अन्तिम संस्करण",
  "Correction Process": "सुधार प्रक्रिया",
  "Good Research Practice": "राम्रो अनुसन्धान अभ्यास",
  "Research Centre": "अनुसन्धान केन्द्र",
  "Research Design": "अनुसन्धान डिजाइन",
  "Data collection": "डाटा संकलन",
  "Data collection methods": "डाटा संकलन विधिहरू",
  "Data analysis": "डाटा विश्लेषण",
  "Statistical analysis": "सांख्यिकीय विश्लेषण",
  "Data Management": "डाटा व्यवस्थापन",
  "Statistical Analysis": "सांख्यिकीय विश्लेषण",
  "Participant Information": "सहभागी जानकारी",
  "Informed Consent": "सूचित सहमति",
  References: "सन्दर्भहरू",
  Referencing: "सन्दर्भ व्यवस्थापन",
  Formatting: "फर्म्याटिङ",
  Submission: "पेश",
  Evaluation: "मूल्याङ्कन",
  "Viva Voce": "मौखिक परीक्षा",
  Plagiarism: "साहित्यिक चोरी",
  Originality: "मौलिकता",
  Approval: "स्वीकृति",
  Supervisor: "पर्यवेक्षक",
  Supervision: "पर्यवेक्षण",
  "Introduction and Background": "परिचय तथा पृष्ठभूमि",
  "Background of the research topic": "अनुसन्धान विषयको पृष्ठभूमि",
  "Study setting": "अध्ययनको परिवेश",
  "Research population": "अनुसन्धान जनसंख्या",
  "Sampling approach": "नमुना छनोट विधि",
  "Data sources": "डाटा स्रोतहरू",
  "Data analysis methods": "डाटा विश्लेषण विधिहरू",
  "Ethical consideration": "नैतिक विचार",
  "Supporting Material": "सहायक सामग्री",
  "Supporting documents": "सहायक कागजातहरू",
  "Expected outcomes": "अपेक्षित नतिजाहरू",
  "Expected outputs": "अपेक्षित उपलब्धिहरू",
  "Cover page": "कभर पृष्ठ",
  Keywords: "मुख्य शब्दहरू",
  Introduction: "परिचय",
  Hypothesis: "परिकल्पना",
  "Work plan": "कार्य योजना",
  Budget: "बजेट",
  Annexes: "परिशिष्टहरू",
  Appendices: "परिशिष्टहरू",
  Objectives: "उद्देश्यहरू",
  Rationale: "औचित्य",
  "Methods and procedures": "विधि तथा प्रक्रियाहरू",
  "Population, sampling and tools": "जनसंख्या, नमुना तथा उपकरणहरू",
  "Results / findings": "नतिजा / निष्कर्षहरू",
  Conclusion: "निष्कर्ष",
  "Conclusion and Recommendations": "निष्कर्ष तथा सिफारिसहरू",
  "Research and extension": "अनुसन्धान तथा विस्तार",
  "Research and Extension": "अनुसन्धान तथा विस्तार",
  Agriculture: "कृषि",
  "Animal sciences": "पशु विज्ञान",
  Forestry: "वन विज्ञान",
  Aquaculture: "जलचर पालन",
  "Socio-economics": "सामाजिक-आर्थिक अध्ययन",
  "Clear and concise research title": "स्पष्ट तथा संक्षिप्त अनुसन्धान शीर्षक",
};

const wordMap: Record<string, string> = {
  research: "अनुसन्धान",
  university: "विश्वविद्यालय",
  thesis: "थेसिस",
  dissertation: "डिसर्टेसन",
  proposal: "प्रस्ताव",
  study: "अध्ययन",
  academic: "शैक्षिक",
  student: "विद्यार्थी",
  students: "विद्यार्थीहरू",
  requirements: "आवश्यकताहरू",
  requirement: "आवश्यकता",
  process: "प्रक्रिया",
  guidelines: "निर्देशनहरू",
  guideline: "निर्देशन",
  methodology: "अनुसन्धान विधि",
  methods: "विधिहरू",
  method: "विधि",
  literature: "साहित्य",
  review: "समीक्षा",
  data: "डाटा",
  analysis: "विश्लेषण",
  ethical: "नैतिक",
  ethics: "नैतिकता",
  approval: "स्वीकृति",
  supervisor: "पर्यवेक्षक",
  department: "विभाग",
  programme: "कार्यक्रम",
  program: "कार्यक्रम",
  faculty: "संकाय",
  submission: "पेश",
  formatting: "फर्म्याटिङ",
  references: "सन्दर्भहरू",
  source: "स्रोत",
  sources: "स्रोतहरू",
  results: "नतिजाहरू",
  findings: "निष्कर्षहरू",
  objectives: "उद्देश्यहरू",
  questions: "प्रश्नहरू",
  question: "प्रश्न",
  background: "पृष्ठभूमि",
  introduction: "परिचय",
  context: "सन्दर्भ",
  purpose: "उद्देश्य",
  participants: "सहभागीहरू",
  participant: "सहभागी",
  consent: "सहमति",
  plagiarism: "साहित्यिक चोरी",
  original: "मौलिक",
  final: "अन्तिम",
  important: "महत्वपूर्ण",
  information: "जानकारी",
  document: "कागजात",
  documents: "कागजातहरू",
  title: "शीर्षक",
  page: "पृष्ठ",
  pages: "पृष्ठहरू",
  chapter: "अध्याय",
  chapters: "अध्यायहरू",
  structure: "संरचना",
  procedure: "प्रक्रिया",
  procedures: "प्रक्रियाहरू",
  progress: "प्रगति",
  reporting: "प्रतिवेदन",
  evaluation: "मूल्याङ्कन",
  internal: "आन्तरिक",
  external: "बाह्य",
  presentation: "प्रस्तुति",
  health: "स्वास्थ्य",
  clinical: "क्लिनिकल",
  human: "मानव",
  animal: "पशु",
  risk: "जोखिम",
  risks: "जोखिमहरू",
  confidentiality: "गोपनीयता",
  voluntary: "स्वैच्छिक",
  contact: "सम्पर्क",
  website: "वेबसाइट",
  official: "आधिकारिक",
  current: "हालको",
  latest: "नवीनतम",
  applicable: "लागू हुने",
  where: "जहाँ",
  required: "आवश्यक",
  relevant: "सम्बन्धित",
  develop: "विकास गर्नु",
  prepare: "तयार गर्नु",
  submit: "पेश गर्नु",
  complete: "पूरा गर्नु",
  check: "जाँच गर्नु",
  confirm: "पुष्टि गर्नु",
  use: "प्रयोग गर्नु",
  follow: "पालना गर्नु",
  maintain: "कायम राख्नु",
  obtain: "प्राप्त गर्नु",
  identify: "पहिचान गर्नु",
  include: "समावेश गर्नु",
  includes: "समावेश गर्दछ",
  may: "सक्छ",
  should: "गर्नुपर्छ",
  can: "सक्छ",
  and: "र",
  or: "वा",
  the: "",
  a: "एक",
  an: "एक",
  of: "को",
  for: "का लागि",
  with: "सँग",
  in: "मा",
  on: "मा",
  from: "बाट",
  to: "लाई",
  before: "अघि",
  after: "पछि",
  according: "अनुसार",
  through: "मार्फत",
  based: "आधारित",
  published: "प्रकाशित",
  provided: "प्रदान गरिएको",
  available: "उपलब्ध",
  different: "फरक",
  specific: "विशिष्ट",
  major: "प्रमुख",
  related: "सम्बन्धित",
  appropriate: "उपयुक्त",
  work: "कार्य",
  working: "काम गर्दै",
  completed: "पूरा गरिएको",
};

export function nepaliText(value: string): string {
  let result = value;
  for (const [from, to] of Object.entries(phrases).sort(
    (a, b) => b[0].length - a[0].length,
  )) {
    result = result.split(from).join(to);
  }
  for (const [from, to] of Object.entries(wordMap).sort(
    (a, b) => b[0].length - a[0].length,
  )) {
    result = result.replace(new RegExp(`\\b${from}\\b`, "gi"), to);
  }
  return result.replace(/\s{2,}/g, " ").trim();
}

export function localizeUniversity(
  university: UniversityGuideline,
  language: "en" | "ne",
): UniversityGuideline {
  if (language === "en") return university;
  return {
    ...university,
    name: universityNames[university.slug] ?? nepaliText(university.name),
    description: nepaliText(university.description),
    verificationNote: nepaliText(university.verificationNote),
    sections: university.sections.map((section) => ({
      ...section,
      title: nepaliText(section.title),
      description: nepaliText(section.description),
      items: section.items?.map(nepaliText),
      details: section.details?.map((detail) => ({
        ...detail,
        title: nepaliText(detail.title),
        description: detail.description
          ? nepaliText(detail.description)
          : detail.description,
        bullets: detail.bullets?.map(nepaliText),
      })),
    })),
  };
}
